# Generated by Django 2.0.1 on 2018-01-09 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscrapers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reddititem',
            name='id',
        ),
        migrations.AlterField(
            model_name='reddititem',
            name='api_ID',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
