# Generated by Django 2.0.1 on 2018-01-09 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscrapers', '0002_auto_20180109_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reddititem',
            name='api_ID',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
